### ISSUE TITLE
Create @glif/error-logger package

### ISSUE THREAD

**Issue by Schwartz10** [glifio/modules#155]
Hey @navFooh - would love to move your error logger logic into its own package. this is an example of creating a new package in this repo (https://github.com/glifio/modules/pull/139/files tho this never got merged)

If you like sentry, would you mind setting this up in the way you think best suits the needs of Glif? I'm down to talk about "events" in this error context too if you dont have a go-to strategy you recommend / have used in the past that works well

One thing to keep in mind, sentry has some default nextjs handling, but we need to make sure the error logger works on any static javascript application (we are planning to build the glif apps statically).

Then we can add the error reporting to:

- Tx history in the react-components
- Glif wallet
- Safe
- Verifier
- Message explorer app (which we'll build shortly)

I can handle adding the error reporting to the various apps since that's kind of a pain in the ass to do... 

I'll DM you a password to our sentry account

**Comment by navFooh** [comment]
https://github.com/glifio/modules/pull/156
