### ISSUE TITLE
TS2688 error on filecoin-wallet-provider 

### ISSUE THREAD

**Issue by hwnahm** [glifio/modules#7]
node_modules/@glif/filecoin-wallet-provider/dist/filecoin.d.ts:1:23 - error TS2688: Cannot find type definition file for 'glif__filecoin-rpc-client'.

1 /// <reference types="glif__filecoin-rpc-client" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@glif/filecoin-wallet-provider/dist/providers/local-node-provider.d.ts:1:23 - error TS2688: Cannot find type definition file for 'glif__filecoin-rpc-client'.

1 /// <reference types="glif__filecoin-rpc-client" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Schwartz10** [comment]
Will get fixed with https://github.com/glifio/modules/pull/14
