### ISSUE TITLE
filecoin-message TypeError

### ISSUE THREAD

**Issue by hwnahm** [glifio/modules#8]
const message = new Message({
  to: 't03832874859695014541',
  from: 't1pyfq7dg6sq65acyomqvzvbgwni4zllglqffw5dy',
  nonce: 1,
  value: new BigNumber('1000000000'),
  method: 0
})

--> TypeError: Message is not a constructor

**Comment by Schwartz10** [comment]
Interesting @hwnahm ! 

I think this is related to https://github.com/glifio/modules/issues/12

A couple things to try:

`const {Message} = require('@glif/filecoin-message')`
`import {Message} from '@glif/filecoin-message'`

_instead of_ importing from default

**Comment by Schwartz10** [comment]
Hey @hwnahm - you can give `@glif/filecoin-message@1.1.0-beta.4` a try
